// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"git.code.oa.com/trpc-go/trpc-config-wuji"
	"git.code.oa.com/trpc-go/trpc-database/gorm"
	"git.code.oa.com/trpc-go/trpc-database/mysql"
	"git.code.oa.com/trpc-go/trpc-go/log"
	"git.woa.com/trpcprotocol/magic/oncall_agent_oncall_agent_debug"
	"git.woa.com/video_pay_middle_platform/pay-go-comm/utils"
	"git.woa.com/video_pay_oss/magic_group/oncall_agent/domain/agents/cdkagent"
	"git.woa.com/video_pay_oss/magic_group/oncall_agent/domain/agents/codeanalysis"
	"git.woa.com/video_pay_oss/magic_group/oncall_agent/domain/agents/magiconcall"
	"git.woa.com/video_pay_oss/magic_group/oncall_agent/domain/interfaces/external"
	"git.woa.com/video_pay_oss/magic_group/oncall_agent/domain/model"
	"git.woa.com/video_pay_oss/magic_group/oncall_agent/domain/tools/cdkeyquery"
	"git.woa.com/video_pay_oss/magic_group/oncall_agent/domain/tools/lingshanquery"
	"git.woa.com/video_pay_oss/magic_group/oncall_agent/domain/tools/logquery"
	"git.woa.com/video_pay_oss/magic_group/oncall_agent/domain/tools/magictool"
	"git.woa.com/video_pay_oss/magic_group/oncall_agent/domain/tools/mcptool"
	"git.woa.com/video_pay_oss/magic_group/oncall_agent/domain/tools/traceanalysis"
	"git.woa.com/video_pay_oss/magic_group/oncall_agent/infrastructure/config/rainbow"
	wuji2 "git.woa.com/video_pay_oss/magic_group/oncall_agent/infrastructure/config/wuji"
	"git.woa.com/video_pay_oss/magic_group/oncall_agent/infrastructure/external/http/cdkey"
	"git.woa.com/video_pay_oss/magic_group/oncall_agent/infrastructure/external/http/galileo"
	"git.woa.com/video_pay_oss/magic_group/oncall_agent/infrastructure/external/http/lingshan"
	"git.woa.com/video_pay_oss/magic_group/oncall_agent/infrastructure/external/http/magiccli"
	"git.woa.com/video_pay_oss/magic_group/oncall_agent/infrastructure/external/trpc/conditionlog"
	"git.woa.com/video_pay_oss/magic_group/oncall_agent/infrastructure/repo/mysql/magic_config"
	"git.woa.com/video_pay_oss/magic_group/oncall_agent/services/a2a"
	agui2 "git.woa.com/video_pay_oss/magic_group/oncall_agent/services/agui"
	"git.woa.com/video_pay_oss/magic_group/oncall_agent/services/debug"
	"git.woa.com/video_pay_oss/magic_group/oncall_agent/services/sse"
	"git.woa.com/video_pay_oss/magic_group/oncall_agent/services/wecom"
	utils2 "git.woa.com/video_pay_oss/magic_group/oncall_agent/utils"
	"time"
	"trpc.group/trpc-go/trpc-a2a-go/server"
	"trpc.group/trpc-go/trpc-agent-go/agent"
	model2 "trpc.group/trpc-go/trpc-agent-go/model"
	"trpc.group/trpc-go/trpc-agent-go/model/openai"
	"trpc.group/trpc-go/trpc-agent-go/server/agui"
	"trpc.group/trpc-go/trpc-agent-go/session"
	"trpc.group/trpc-go/trpc-agent-go/session/inmemory"
	"trpc.group/trpc-go/trpc-agent-go/session/summary"
	"trpc.group/trpc-go/trpc-agent-go/tool"
	"trpc.group/trpc-go/trpc-agent-go/tool/webfetch/httpfetch"
)

import (
	_ "git.code.oa.com/trpc-go/trpc-config-rainbow"
	_ "git.code.oa.com/trpc-go/trpc-filter/recovery"
	_ "git.code.oa.com/trpc-go/trpc-filter/validation"
	_ "git.code.oa.com/trpc-go/trpc-metrics-runtime"
	_ "git.code.oa.com/trpc-go/trpc-naming-polaris"
	_ "git.woa.com/galileo/trpc-go-galileo"
	_ "git.woa.com/trpc-go/trpc-agent-go/trpc"
	_ "git.woa.com/trpc-go/trpc-agent-go/trpc/telemetry/galileo"
	_ "git.woa.com/video-libs/trpc-jce-compatible"
	_ "git.woa.com/video_pay_middle_platform/pay-go-comm/tcache/filter/infcache"
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// InitApp wires all dependencies and returns the App.
// cfg is provided by main() after rainbow.Init().
func InitApp(cfg rainbow.AppConfig) (*App, error) {
	model := provideModelInstance(cfg)
	service := provideSessionService(cfg, model)
	wujiAPI, err := provideWujiCli()
	if err != nil {
		return nil, err
	}
	api, err := provideMCPTool(wujiAPI, cfg)
	if err != nil {
		return nil, err
	}
	genConfig := provideGenConfig(cfg)
	galileoAPI := provideGalileoCli(cfg)
	lingshanAPI := provideLingshanCli(cfg)
	conditionLogAPI := provideConditionLogCli()
	traceConfig := provideTraceConfig(cfg)
	magicConfigAPI, err := provideMagicConfigAPI()
	if err != nil {
		return nil, err
	}
	magicCliAPI := provideMagicCliAPI()
	dep := provideMagicToolDep(wujiAPI, magicConfigAPI, magicCliAPI)
	magiconcallDep, err := provideMagicAgentDep(model, wujiAPI, api, genConfig, galileoAPI, lingshanAPI, conditionLogAPI, traceConfig, dep)
	if err != nil {
		return nil, err
	}
	cdkeyAPI := provideCdkeyCli(cfg)
	cdkagentDep := provideCdkeyAgentDep(model, wujiAPI, api, genConfig, cdkeyAPI)
	app, err := provideApp(cfg, service, magiconcallDep, cdkagentDep, dep)
	if err != nil {
		return nil, err
	}
	return app, nil
}

// wire.go:

// App holds all registered tRPC services
type App struct {
	A2AServers  map[string]*server.A2AServer
	SSEServers  map[string]sse.API
	AguiServers map[string]*agui.Server
	WeComServer *wecom.Server // 企微WeCom AI Bot服务, 可能为nil(未启用时)
	DebugSrv    oncall_agent_oncall_agent_debug.DebugService
}

func provideGenConfig(cfg rainbow.AppConfig) model.GenConfig {
	return model.GenConfig{
		Temperature: cfg.Temperature,
		TopP:        cfg.TopP,
	}
}

func provideModelInstance(cfg rainbow.AppConfig) *openai.Model {

	if cfg.ModelContextWindow > 0 {
		model2.RegisterModelContextWindow(cfg.OpenAIModelName, cfg.ModelContextWindow)
		log.Infof("registered model context window: model=%s, window=%d",
			cfg.OpenAIModelName, cfg.ModelContextWindow)
	}

	return openai.New(cfg.OpenAIModelName, openai.WithBaseURL(cfg.OpenAIBaseURL), openai.WithAPIKey(cfg.OpenAIAPIKey), openai.WithEnableTokenTailoring(true))
}

func provideWujiCli() (model.WujiAPI, error) {
	wujiMCPCli, err := wuji.NewFilter("mcp_tool", []string{"valid"}, "valid=1", wuji2.MCPTool{})
	if err != nil {
		return nil, err
	}
	agentConfigCli, err := wuji.NewFilter("agent_config", []string{"name"}, "is_valid=1", wuji2.AgentConfig{})
	if err != nil {
		return nil, err
	}
	localToolCli, err := wuji.NewFilter("local_tool", []string{"name"}, "", wuji2.LocalToolConfig{})
	if err != nil {
		return nil, err
	}
	return wuji2.New(wujiMCPCli, agentConfigCli, localToolCli), nil
}

func provideMagicConfigAPI() (external.MagicConfigAPI, error) {

	dbTest, err := gorm.NewClientProxy("trpc.magic.oncall_agent.magic_db_test")
	if err != nil {
		return nil, err
	}
	dbFormal, err := gorm.NewClientProxy("trpc.magic.oncall_agent.magic_db_formal")
	if err != nil {
		return nil, err
	}

	if !utils.IsFormalEnv() {
		dbTest = dbTest.Debug()
	}
	return magicconfig.New(dbTest, dbFormal), nil
}

func provideGalileoCli(cfg rainbow.AppConfig) external.GalileoAPI {
	return galileo.New(cfg.BkAppCode, cfg.BkAppToken)
}

func provideLingshanCli(cfg rainbow.AppConfig) external.LingshanAPI {
	return lingshan.New(cfg.XGatewaySecretID, cfg.XGatewaySecretKey)
}

func provideCdkeyCli(cfg rainbow.AppConfig) external.CdkeyAPI {
	return cdkey.New(cfg.ESUsername, cfg.ESPassword, cfg.FlowPath)
}

func provideConditionLogCli() external.ConditionLogAPI {
	return conditionlog.New()
}

func provideMagicCliAPI() external.MagicCliAPI {
	return magiccli.New()
}

func provideMCPTool(wujiCli model.WujiAPI, cfg rainbow.AppConfig) (mcptool.API, error) {
	return mcptool.NewMCPToolImpl(context.Background(), wujiCli, &cfg)
}

func provideTraceConfig(cfg rainbow.AppConfig) traceanalysis.TraceConfig {
	return traceanalysis.TraceConfig{
		MaxTraceDepth:          cfg.MaxTraceDepth,
		MaxSpanNum:             cfg.MaxSpanNum,
		MaxSpanLogLength:       cfg.MaxSpanLogLength,
		SelfTeamName:           cfg.SelfTeamName,
		OtherTeamTruncateDepth: cfg.OtherTeamTruncateDepth,
	}
}

func provideMagicToolDep(w model.WujiAPI, mc external.MagicConfigAPI, m external.MagicCliAPI) magictool.Dep {
	return magictool.Dep{WujiCli: w, MagicConfigCli: mc, MagicCliAPI: m}
}

// getLocalToolDescWire is a helper (not a Wire provider) used inside provide*AgentDep functions.
func getLocalToolDescWire(wujiCli model.WujiAPI, name string) string {
	cfg := wujiCli.GetLocalToolConfig(name)
	if cfg != nil && cfg.Description != "" {
		return cfg.Description
	}
	return ""
}

// provideMagicAgentDep provides the unified magic oncall agent dependencies
// Merged from magiconcall and magic_config_agent
func provideMagicAgentDep(
	m *openai.Model,
	w model.WujiAPI,
	mcp mcptool.API,
	gc model.GenConfig, galileo2 external.GalileoAPI, lingshan2 external.LingshanAPI,

	condLog external.ConditionLogAPI,
	traceConfig traceanalysis.TraceConfig,
	magicToolDep magictool.Dep,
) (magiconcall.Dep, error) {

	traceTool := traceanalysis.New(traceanalysis.Dep{
		GalileoCli: galileo2, LingshanCli: lingshan2, ConditionLogCli: condLog, WujiCli: w, Cfg: traceConfig,
	})
	logQueryTool := logquery.New(logquery.Dep{GalileoCli: galileo2, WujiCli: w})
	lingshanQueryTool := lingshanquery.New(lingshanquery.Dep{LingshanCli: lingshan2, WujiCli: w})
	base64Tool := utils2.NewBase64Tool(getLocalToolDescWire(w, "base64_decode"))
	dt2tsTool := utils2.NewDateTimeToTimestampMSTool(getLocalToolDescWire(w, "date_time_to_timestamp_ms"))
	ts2dtTool := utils2.NewTimestampMSToDateTimeTool(getLocalToolDescWire(w, "timestamp_ms_to_date_time"))

	webFetchTool := httpfetch.NewTool(httpfetch.WithMaxContentLength(20000), httpfetch.WithMaxTotalContentLength(50000))

	modTypeTool := magictool.NewMagicModTypeInfoTool(magicToolDep)
	actInfoTool := magictool.NewMagicActInfoTool(magicToolDep)

	codeAnalysisTool, err := codeanalysis.NewCodeAnalysisAgentTool(codeanalysis.Dep{
		ModelInstance: m, WujiCli: w, MCPTool: mcp, GenConfig: gc,
		LocalTools: []tool.Tool{logQueryTool, lingshanQueryTool, dt2tsTool, ts2dtTool, base64Tool},
	})
	if err != nil {
		return magiconcall.Dep{}, err
	}

	return magiconcall.Dep{
		ModelInstance: m, WujiCli: w, MCPTool: mcp, GenConfig: gc,
		LocalTools: []tool.Tool{

			traceTool, logQueryTool, codeAnalysisTool,
			base64Tool, lingshanQueryTool, dt2tsTool, ts2dtTool,

			modTypeTool, actInfoTool, webFetchTool,
		},
	}, nil
}

func provideCdkeyAgentDep(
	m *openai.Model,
	w model.WujiAPI,
	mcp mcptool.API,
	gc model.GenConfig, cdkey2 external.CdkeyAPI,

) cdkagent.Dep {
	cdkeyQueryTool := cdkeyquery.New(cdkeyquery.Dep{CdkeyCli: cdkey2, WujiCli: w})
	dt2tsTool := utils2.NewDateTimeToTimestampMSTool(getLocalToolDescWire(w, "date_time_to_timestamp_ms"))
	ts2dtTool := utils2.NewTimestampMSToDateTimeTool(getLocalToolDescWire(w, "timestamp_ms_to_date_time"))
	return cdkagent.Dep{
		ModelInstance: m, WujiCli: w, MCPTool: mcp, GenConfig: gc,
		LocalTools: []tool.Tool{cdkeyQueryTool, dt2tsTool, ts2dtTool},
	}
}

func provideSessionService(cfg rainbow.AppConfig, m *openai.Model) session.Service {
	summarizer := summary.NewSummarizer(m, summary.WithChecksAny(summary.CheckEventThreshold(cfg.SummarizeEventThreshold), summary.CheckTokenThreshold(cfg.SummarizeTokenThreshold), summary.CheckTimeThreshold(time.Duration(cfg.SummarizeTimeThreshold)*time.Minute)),
	)
	return inmemory.NewSessionService(inmemory.WithSummarizer(summarizer), inmemory.WithSessionEventLimit(cfg.SummarizeEventThreshold*2))
}

// provideApp constructs all agents and tRPC services, returning the complete App.
// All agent New() functions return the same agent.Agent interface, so Wire cannot
// disambiguate them. This single function receives each Dep struct (unique types) from Wire
// and calls New() manually for each agent.
func provideApp(
	cfg rainbow.AppConfig,
	sessionSvc session.Service,
	magicAgentDep magiconcall.Dep,
	cdkeyDep cdkagent.Dep,
	magicToolDep magictool.Dep,
) (*App, error) {
	magicAgt, err := magiconcall.New(magicAgentDep)
	if err != nil {
		return nil, err
	}
	cdkAgt, err := cdkagent.New(cdkeyDep)
	if err != nil {
		return nil, err
	}

	mysqlCli := mysql.NewClientProxy(mysqlFeedbackName)
	sseServers := map[string]sse.API{
		sseServiceName:      sse.NewSSEService(sessionSvc, magicAgt, mysqlCli, "magic_oncall_agent", cfg.Debug),
		cdkeySSEServiceName: sse.NewSSEService(sessionSvc, cdkAgt, mysqlCli, "cdkey_oncall_agent", cfg.Debug),
	}

	a2aSrv, err := a2a.NewA2AServer(a2aServiceName, magicAgt, sessionSvc)
	if err != nil {
		return nil, err
	}

	aguiSrv, err := agui2.New(magicAgt, sessionSvc)
	if err != nil {
		return nil, err
	}

	// 企微WeCom AI Bot服务 (按配置决定是否启用)
	var wecomSrv *wecom.Server
	if cfg.WeComEnabled {
		wecomSrv, err = wecom.New("oncall_agent", magicAgt, wecom.Config{
			BotID:         cfg.WeComStreamBotID,
			Secret:        cfg.WeComStreamSecret,
			BotName:       cfg.WeComBotName,
			WebSocketURL:  cfg.WeComStreamWSURL,
			EnableStream:  cfg.WeComEnableStream,
			ShowToolCalls: cfg.WeComShowToolCalls,
		})
		if err != nil {
			log.Warnf("WeCom server creation failed (disabled): %v", err)
			wecomSrv = nil
		}
	}

	return &App{
		A2AServers:  map[string]*server.A2AServer{a2aServiceName: a2aSrv},
		SSEServers:  sseServers,
		AguiServers: map[string]*agui.Server{aguiServiceName: aguiSrv},
		WeComServer: wecomSrv,
		DebugSrv:    debug.New(magicToolDep),
	}, nil
}

// Ensure agent import is used (agent.Agent is referenced in provideApp return values).
var _ agent.Agent
