// Code generated by trpc-go/trpc-go-cmdline v2.8.75. DO NOT EDIT.
// source: log_collector.proto

package proto

import (
	"context"
	"errors"
	"fmt"

	_ "git.code.oa.com/trpc-go/trpc-go"
	"git.code.oa.com/trpc-go/trpc-go/client"
	"git.code.oa.com/trpc-go/trpc-go/codec"
	_ "git.code.oa.com/trpc-go/trpc-go/http"
	"git.code.oa.com/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// LogCollectorService defines service.
type LogCollectorService interface {
	// ReportTrace reports prompt execution trace data.
	ReportTrace(ctx context.Context, req *ReportTraceRequest) (*ReportTraceResponse, error)
}

func LogCollectorService_ReportTrace_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReportTraceRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(LogCollectorService).ReportTrace(ctx, reqbody.(*ReportTraceRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// LogCollectorServer_ServiceDesc descriptor for server.RegisterService.
var LogCollectorServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.trs.prompt_log_collector.LogCollector",
	HandlerType: ((*LogCollectorService)(nil)),
	Methods: []server.Method{
		{
			Name: "/trpc.trs.prompt_log_collector.LogCollector/ReportTrace",
			Func: LogCollectorService_ReportTrace_Handler,
		},
	},
}

// RegisterLogCollectorService registers service.
func RegisterLogCollectorService(s server.Service, svr LogCollectorService) {
	if err := s.Register(&LogCollectorServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("LogCollector register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedLogCollector struct{}

// ReportTrace reports prompt execution trace data.
func (s *UnimplementedLogCollector) ReportTrace(ctx context.Context, req *ReportTraceRequest) (*ReportTraceResponse, error) {
	return nil, errors.New("rpc ReportTrace of service LogCollector is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// LogCollectorClientProxy defines service client proxy
type LogCollectorClientProxy interface {
	// ReportTrace reports prompt execution trace data.
	ReportTrace(ctx context.Context, req *ReportTraceRequest, opts ...client.Option) (rsp *ReportTraceResponse, err error)
}

type LogCollectorClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewLogCollectorClientProxy = func(opts ...client.Option) LogCollectorClientProxy {
	return &LogCollectorClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *LogCollectorClientProxyImpl) ReportTrace(ctx context.Context, req *ReportTraceRequest, opts ...client.Option) (*ReportTraceResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.trs.prompt_log_collector.LogCollector/ReportTrace")
	msg.WithCalleeServiceName(LogCollectorServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("trs")
	msg.WithCalleeServer("prompt_log_collector")
	msg.WithCalleeService("LogCollector")
	msg.WithCalleeMethod("ReportTrace")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &ReportTraceResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
