// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.24.2
// source: log_collector.proto

package proto

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ReportTraceRequest is the request for reporting one trace.
type ReportTraceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Caller is the caller service name, formatted as trpc.${app}.${server}.
	Caller string `protobuf:"bytes,1,opt,name=caller,proto3" json:"caller,omitempty"`
	// TraceJson is the prompt execution trace encoded as JSON.
	TraceJson string `protobuf:"bytes,2,opt,name=trace_json,json=traceJson,proto3" json:"trace_json,omitempty"`
	// Token is the business isolation token used to partition trace data.
	Token string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *ReportTraceRequest) Reset() {
	*x = ReportTraceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_log_collector_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportTraceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTraceRequest) ProtoMessage() {}

func (x *ReportTraceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_log_collector_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTraceRequest.ProtoReflect.Descriptor instead.
func (*ReportTraceRequest) Descriptor() ([]byte, []int) {
	return file_log_collector_proto_rawDescGZIP(), []int{0}
}

func (x *ReportTraceRequest) GetCaller() string {
	if x != nil {
		return x.Caller
	}
	return ""
}

func (x *ReportTraceRequest) GetTraceJson() string {
	if x != nil {
		return x.TraceJson
	}
	return ""
}

func (x *ReportTraceRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// ReportTraceResponse is the response for reporting one trace.
type ReportTraceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Code is zero on success and non-zero on failure.
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// Message contains the error message when code is non-zero.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ReportTraceResponse) Reset() {
	*x = ReportTraceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_log_collector_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportTraceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTraceResponse) ProtoMessage() {}

func (x *ReportTraceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_log_collector_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTraceResponse.ProtoReflect.Descriptor instead.
func (*ReportTraceResponse) Descriptor() ([]byte, []int) {
	return file_log_collector_proto_rawDescGZIP(), []int{1}
}

func (x *ReportTraceResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ReportTraceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_log_collector_proto protoreflect.FileDescriptor

var file_log_collector_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6c, 0x6f, 0x67, 0x5f, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1d, 0x74, 0x72, 0x70, 0x63, 0x2e, 0x74, 0x72, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x5f, 0x6c, 0x6f, 0x67, 0x5f, 0x63, 0x6f, 0x6c, 0x6c, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x22, 0x61, 0x0a, 0x12, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x72,
	0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x61,
	0x6c, 0x6c, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x61, 0x6c, 0x6c,
	0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x72, 0x61, 0x63, 0x65, 0x5f, 0x6a, 0x73, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x72, 0x61, 0x63, 0x65, 0x4a, 0x73, 0x6f,
	0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x43, 0x0a, 0x13, 0x52, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x54, 0x72, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x84, 0x01, 0x0a,
	0x0c, 0x4c, 0x6f, 0x67, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x74, 0x0a,
	0x0b, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x72, 0x61, 0x63, 0x65, 0x12, 0x31, 0x2e, 0x74,
	0x72, 0x70, 0x63, 0x2e, 0x74, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x5f, 0x6c,
	0x6f, 0x67, 0x5f, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x52, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x54, 0x72, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x32, 0x2e, 0x74, 0x72, 0x70, 0x63, 0x2e, 0x74, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x6d, 0x70,
	0x74, 0x5f, 0x6c, 0x6f, 0x67, 0x5f, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e,
	0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x72, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x4b, 0x5a, 0x49, 0x67, 0x69, 0x74, 0x2e, 0x77, 0x6f, 0x61, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x74, 0x72, 0x70, 0x63, 0x2d, 0x67, 0x6f, 0x2f, 0x74, 0x72, 0x70, 0x63, 0x2d,
	0x61, 0x67, 0x65, 0x6e, 0x74, 0x2d, 0x67, 0x6f, 0x2f, 0x74, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x65, 0x6e, 0x67, 0x69, 0x6e,
	0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_log_collector_proto_rawDescOnce sync.Once
	file_log_collector_proto_rawDescData = file_log_collector_proto_rawDesc
)

func file_log_collector_proto_rawDescGZIP() []byte {
	file_log_collector_proto_rawDescOnce.Do(func() {
		file_log_collector_proto_rawDescData = protoimpl.X.CompressGZIP(file_log_collector_proto_rawDescData)
	})
	return file_log_collector_proto_rawDescData
}

var file_log_collector_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_log_collector_proto_goTypes = []interface{}{
	(*ReportTraceRequest)(nil),  // 0: trpc.trs.prompt_log_collector.ReportTraceRequest
	(*ReportTraceResponse)(nil), // 1: trpc.trs.prompt_log_collector.ReportTraceResponse
}
var file_log_collector_proto_depIdxs = []int32{
	0, // 0: trpc.trs.prompt_log_collector.LogCollector.ReportTrace:input_type -> trpc.trs.prompt_log_collector.ReportTraceRequest
	1, // 1: trpc.trs.prompt_log_collector.LogCollector.ReportTrace:output_type -> trpc.trs.prompt_log_collector.ReportTraceResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_log_collector_proto_init() }
func file_log_collector_proto_init() {
	if File_log_collector_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_log_collector_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportTraceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_log_collector_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportTraceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_log_collector_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_log_collector_proto_goTypes,
		DependencyIndexes: file_log_collector_proto_depIdxs,
		MessageInfos:      file_log_collector_proto_msgTypes,
	}.Build()
	File_log_collector_proto = out.File
	file_log_collector_proto_rawDesc = nil
	file_log_collector_proto_goTypes = nil
	file_log_collector_proto_depIdxs = nil
}
